Working on server update

diff --git a/bin/locksmith-servers b/bin/locksmith-servers
--- a/bin/locksmith-servers
+++ b/bin/locksmith-servers
@@ -65,6 +65,43 @@ show() {
     done
 }
 
+status() {
+    sdir=`ensureConfigDir servers`
+    for s in ${*:-`list`}; do
+	echo "$s:"
+	auth=`fileEscape $sdir/$s/authorized_keys`
+	add=`fileEscape $sdir/$s/pending-additions.txt`
+	showKeys $auth | grep EXPIRED 
+
+	if [ -f "$add" ] ; then
+	    echo "keys to add:"
+	    showKeys $add 
+	fi
+	
+    done
+}
+
+update() {
+    sdir=`ensureConfigDir servers`
+    for s in ${*:-`list`}; do
+	verbose "$s:"
+	fetch
+	auth=`fileEscape $sdir/$s/authorized_keys`
+	newauth=`fileEscape $sdir/$s/authorized_keys.new`
+	add=`fileEscape $sdir/$s/pending-additions.txt`
+
+	expired=`getExpiredKeysRegexp`
+
+	cat "$auth" "$add" | perl -n -e "print unless /$expired/" > $newauth
+
+	scp $newauth $s:.ssh/authorized_keys && (mv -f $newauth $auth; rm -f $add; echo "$s updated") || echo "$s update failed"
+
+	if [ -f $file ] ; then
+	    showKeys "$auth"
+	fi
+    done
+}
+
 add-key() {
     if [ $# -lt 1 ] ; then
 	echo "You must specifiy a key to add"
@@ -72,6 +109,7 @@ add-key() {
     fi
 
     key=`findKey $1`
+    shift
 
     sdir=`ensureConfigDir servers`
     for s in ${*:-`list`}; do
